
name: React Testing CI

on:
  push:
    branches: [ dev,cicd ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [14.x, 16.x]
        
    steps:
    - uses: actions/checkout@v2
    # - name: Use Node.js ${{ matrix.node-version }}
    - name: starting npm install 
      uses: actions/setup-node@v2
      with:
        # node-version: ${{ matrix.node-version }}
        node-version: 16.x
        cache: 'npm'
    - run: npm install
    
    # - name: start lint
    #   uses: actions/setup-node@v2
    # - run: npm install eslint --save-dev 
    # - run: npm run lint-check
    
    - name: start testing
      uses: actions/setup-node@v2
    - run: npm run test -- --watchAll=false --passWithNoTests



  # lint: 

  #   runs-on: ubuntu-latest

  #   needs: [build]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: start linting process
  #     uses: actions/setup-node@v2
  #   - run: npm install eslint --save-dev 
  #   - run: npm run lint-check

  # test: 

  #   runs-on: ubuntu-latest

  #   needs: [build,lint]
  #   steps:
  #   - uses: actions/checkout@v2 
  #   - name: start testing process
  #     uses: actions/setup-node@v2
  #   - run: npm run test -- --watchAll=false --passWithNoTests
